kind: Service
apiVersion: v1
metadata:
  name: bugbountytest23
spec:
  selector:
    app: helloserver2
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugbountytest23
  labels:
    app: helloserver2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloserver2
  template:
    metadata:
      labels:
        app: helloserver2
    spec:
      imagePullSecrets:
      - name: bugbountytest2
      containers:
      - name: helloserver
        image: jarkkotesti/update-container2
        ports:
        - containerPort: 80
