apiVersion: batch/v1
kind: Job
metadata:
  name: update-job
spec:
  template:
    spec:
      containers:
      - name: update-container3
        image: jarkkotesti/update-container3:latest
        volumeMounts:
        - name: host-root
          mountPath: /host-root
      restartPolicy: Never
      volumes:
      - name: host-root
        hostPath:
          path: /
