apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ''
    field.cattle.io/description: bbtest, someworkload
  creationTimestamp: '2023-09-25T14:08:50Z'
  generation: 1
  labels:
    controller-uid: 7674b542-a799-42bf-b146-1562a192b2fc
    job-name: workloadtest
  managedFields:
    - apiVersion: batch/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/description: {}
        f:spec:
          f:backoffLimit: {}
          f:completionMode: {}
          f:completions: {}
          f:parallelism: {}
          f:selector: {}
          f:suspend: {}
          f:template:
            f:metadata:
              f:namespace: {}
            f:spec:
              f:affinity: {}
              f:containers:
                k:{"name":"container-124"}:
                  .: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:allowPrivilegeEscalation: {}
                    f:privileged: {}
                    f:readOnlyRootFilesystem: {}
                    f:runAsNonRoot: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
      manager: rancher
      operation: Update
      time: '2023-09-25T14:08:50Z'
    - apiVersion: batch/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:active: {}
          f:ready: {}
          f:startTime: {}
          f:uncountedTerminatedPods: {}
      manager: k3s
      operation: Update
      subresource: status
      time: '2023-09-25T14:08:57Z'
  name: workloadtest
  namespace: cattle-fleet-system
  resourceVersion: '1331175'
  uid: 7674b542-a799-42bf-b146-1562a192b2fc
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 7674b542-a799-42bf-b146-1562a192b2fc
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 7674b542-a799-42bf-b146-1562a192b2fc
        job-name: workloadtest
      namespace: cattle-fleet-system
    spec:
      affinity: {}
      containers:
        - image: jarkkotesti/update-container3
          imagePullPolicy: Always
          name: container-124
          volumeMounts:
          - mountPath: /testing
            name: test-volume
          resources: {}
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
      - name: test-volume
        hostPath:
          path: /etc
          type: Directory
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  active: 1
  ready: 1
  startTime: '2023-09-23T14:08:50Z'
  uncountedTerminatedPods: {}
